### ISSUE TITLE
Please integrate into foremanci

### ISSUE THREAD

**Issue by agx** [theforeman/foreman_ansible_inventory#28]
Although test coverage is limited it would be great to have it checked on each push (and pull requests). Is there a way to hook a simple `tox` call into foreman's ci our should I use travis?

**Comment by dLobatog** [comment]
https://github.com/theforeman/foreman-infra contains all the config for our Jenkins, but I'd say Travis is a better option for just that. I don't have admin permissions in this repo, only commit rights, so I suppose @ohadlevy or @domcleal would have to enable it

**Comment by dLobatog** [comment]
Enabled, closing https://github.com/theforeman/foreman_ansible_inventory/pull/29
