### ISSUE TITLE
Can't access my hostGroup in my playbook

### ISSUE THREAD

**Issue by AlexisLessard** [theforeman/foreman_ansible_inventory#48]
So i've just installed a test installation of foreman. Really basic, nothing fancy. We just wanted to test the ansible plugin to see its viability (so far so good). Now I'm trying out the foreman dynamic inventory. While I can access all my hosts when i write `hosts: all` in my playbook. However, I can't seem to access a host in a simple group. I've got a host `foo` in the group `ansibleManaged`. But I never receive anything whatever I put in the `hosts` setting. I've tried:

- foreman_ansibleManaged
- ansibleManaged
- foreman_hostgroups_ansibleManaged
- foreman_hostgroup_ansibleManaged

I always receive 
![image](https://cloud.githubusercontent.com/assets/10947093/26010311/63eed14c-371a-11e7-9f0c-81474f3d04c5.png)

How do I select a simple group? I don't have any environment setup, and I know that I can connect to the foreman server because I can connect to my hosts with the `hosts: all` setting. Any idea on what I'm doing wrong?

EDIT: I'm using ansible 2.3

**Comment by AlexisLessard** [comment]
The groups also exists, as I've made a test in postman and got this result
![image](https://cloud.githubusercontent.com/assets/10947093/26011944/f50f1fa0-3720-11e7-86b0-a1b8b72023d7.png)
![image](https://cloud.githubusercontent.com/assets/10947093/26011957/fca70890-3720-11e7-8310-168002d868a9.png)

**Comment by agx** [comment]
On Fri, May 12, 2017 at 10:58:52AM -0700, AlexisLessard wrote:
> So i've just installed a test installation of foreman. Really basic, nothing fancy. We just wanted to test the ansible plugin to see its viability (so far so good). Now I'm trying out the foreman dynamic inventory. While I can access all my hosts when i write `hosts: all` in my playbook. However, I can't seem to access a host in a simple group. I've got a host `foo` in the group `ansibleManaged`. But I never receive anything whatever I put in the `hosts` setting. I've tried:
> 
> - foreman_ansibleManaged
> - ansibleManaged
> - foreman_hostgroups_ansibleManaged
> - foreman_hostgroup_ansibleManaged
> 
> I always receive 
> ![image](https://cloud.githubusercontent.com/assets/10947093/26010311/63eed14c-371a-11e7-9f0c-81474f3d04c5.png)
> 
> How do I select a simple group? I don't have any environment setup, and I know that I can connect to the foreman server because I can connect to my hosts with the `hosts: all` setting. Any idea on what I'm doing wrong?

Check the generated cache file. It has a list of all the available host
groups.

**Comment by AlexisLessard** [comment]
Well, in the cache file, I can certainly see the group name
![image](https://cloud.githubusercontent.com/assets/10947093/26031466/9788f9dc-3842-11e7-9ee3-8e011b3a88bd.png)

However, that's not different from what is shown by the api...wait...let me check the .index file...

![image](https://cloud.githubusercontent.com/assets/10947093/26031472/e604da4a-3842-11e7-96a1-252e82546cb2.png)

The name of the group is reduced in minuscules? Ok... let me try that

**Comment by AlexisLessard** [comment]
Aaaaaaaaand it works! Awesome! Thanks for the tip. Altoug I propose to write this in the README file, please.
