### ISSUE TITLE
Let's archive this repo

### ISSUE THREAD

**Issue by agx** [theforeman/foreman_ansible_inventory#56]
There's currently 3 inventory scripts for foreman around from either foreman or ansible upstream:

1. this one
2. https://github.com/ansible/ansible/blob/devel/contrib/inventory/foreman.py
3. https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/foreman.py

3. lacks features (https://github.com/ansible/ansible/issues/63613, https://github.com/ansible/ansible/issues/63611) that are needed in non trivially small environments , 2. seems mostly up to date and working (with https://github.com/ansible/ansible/pull/63614 and https://github.com/ansible/ansible/pull/63612) while this repository looks mostly dormant. 

So should we close this one and add a note to use the upstream ones? The only thing that keeps me away from that is that ansible upstream is often very complicated to deal with. If we want to keep this repo we should at least update to the version from 2.

**Comment by ares** [comment]
I agree, this repo should be archived, note the warning on the first line of readme. I'll raise it on our community forum as I don't have permissions myself.
